const products = [
    {
        id:1,
        title:'Title',
        price:12,
        topic:'Al',
        image:'../public/fox.jpg',
        rating:2
    },
    {
        id:2,
        title:'Title',
        price:23,
        topic:'her',
        image:'https://wallpapercrafter.com/th800/128829-fox-grass-photography.jpg',
        rating:2
    },
    {
        id:3,
        title:'Dog',
        price:10,
        topic:'Forest',
        image:'https://wallpapercrafter.com/th800/128829-fox-grass-photography.jpg',
        rating:3
    },
    {
        id:4,
        title:'Dog',
        price:100,
        topic:'Fox Kids',
        image:'https://wallpapercrafter.com/th800/128829-fox-grass-photography.jpg',
        rating:3
    },
    {
        id:5,
        title:'Dog',
        price:1,
        topic:'Cats',
        image:'https://wallpapercrafter.com/th800/128829-fox-grass-photography.jpg',
        rating:3
    },
    {
        id:6,
        title:'Fox',
        price:90,
        topic:'Forest',
        image:'https://wallpapercrafter.com/th800/128829-fox-grass-photography.jpg',
        rating:1
    }
]
export default products